
server:
  port: 8002
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/flyshengli/ebid_tyc_config.git    # 配置git仓库的地址                            # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 857307469@qq.com                                        # git仓库的账号
          password: 19891990xy           # git仓库的密码
    bus:
      enabled: true
      trace:
        enabled: true



  rabbitmq:
      host: 111.231.74.132
      port: 15600
      username: ebid
      password: ebid$2019



eureka:
  client:
    service‐url:
      defaultZone: http://localhost:8001/eureka/


management:
  endpoints:
    web:
      exposure:
        include:  bus-refresh

  security:
    enabled: false





