server:
  port: 8001


eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 3
        # 服务失效时间： 如果多久没有收到请求，则可以删除服务
    lease-expiration-duration-in-seconds: 7
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/





